POST http://localhost:3001/api/patients/d27736ec-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

# {
#   "date": "2019-10-20",
#   "specialist": "MD House",
#   "type": "HealthCheck",
#   "description": "Yearly control visit. Cholesterol levels back to normal.",
#   "healthCheckRating": 0
# }
# {
#   "date": "2019-09-10",
#   "specialist": "MD House",
#   "type": "OccupationalHealthcare",
#   "employerName": "FBI",
#   "description": "Prescriptions renewed."
# }
# {
#   "date": "2015-01-02",
#   "type": "Hospital",
#   "specialist": "MD House",
#   "diagnosisCodes": ["S62.5"],
#   "description": "Healing time appr. 2 weeks. patient doesn't remember how he got the injury.",
#   "discharge": {
#     "date": "2015-01-16",
#     "criteria": "Thumb has healed."
#   }
# }
{
  "date": "2019-08-05",
  "type": "OccupationalHealthcare",
  "specialist": "MD House",
  "employerName": "HyPD",
  "diagnosisCodes": ["Z57.1", "Z74.3", "M51.2"],
  "description":
    "Patient mistakenly found himself in a nuclear plant waste site without protection gear. Very minor radiation poisoning. ",
  "sickLeave": {
    "startDate": "2019-08-05",
    "endDate": "2019-08-28"
  }
}